

### GET /
GET http://127.0.0.1:3000 


### GET / items
GET http://127.0.0.1:3000/api/items

### GET / items/:id
GET http://127.0.0.1:3000/api/items/

### delete / items/:id
DELETE http://127.0.0.1:3000/api/items/5

### PUT / items/:id
PUT http://127.0.0.1:3000/api/items/
Content-Type: application/json

{
    "id": 6,
    "name": "tänään tehdään kurkkukeitto"
}


### POST/items
POST  http://127.0.0.1:3000/api/items
Content-Type: application/json
    
{
    "id" : 8,
    "name": "tänään tehdään kurkkukeitto"
}

### POST /items error
POST http://localhost:3000/api/items

{"jotain": "jotain"}


### Media


### GET /
GET http://127.0.0.1:3000/

### GET /
GET http://127.0.0.1:3000/api/media

### GET / media/:id
GET http://127.0.0.1:3000/api/media/9590



### POST/media
POST  http://127.0.0.1:3000/api/media
Content-Type: application/json
    
{
  "filename": "60ac.jpg",
  "title": "New image",
  "description": "The description of the new image",
  "user_id": 305,
  "media_type": "image/jpeg"
}

### PUT / media/:id
PUT http://127.0.0.1:3000/api/media/9590
Content-Type: application/json

{
  "title": "Basement modified",
  "description": "Some new description"
}

### delete / api/media/:id
DELETE http://127.0.0.1:3000/api/media/9590


### User


### GET /user
GET http://127.0.0.1:3000/api/user/

### GET / user/:id
GET http://127.0.0.1:3000/api/user/3609



### POST/user
POST  http://127.0.0.1:3000/api/user
Content-Type: application/json
    
{
 "user_id": 42,
    "username": "Yoda",
    "password": "********",
    "email": "yoda@example.com",
    "user_level_id": 2,
    "created_at": "2023-01-14T06:42:42.000Z"
}

### PUT / user/:id
PUT http://127.0.0.1:3000/api/user/42
Content-Type: application/json

{
    "username": "Yoda2",
    "password": "******************",
    "email": "yoda2@example.com"
}

### delete / user/:id
DELETE http://127.0.0.1:3000/api/user/42